/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface CallExecutionTreeTestInterface extends ethers.utils.Interface {
  functions: {
    "extractTargetFromCallGraph1(bytes,uint256[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "extractTargetFromCallGraph1",
    values: [BytesLike, BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "extractTargetFromCallGraph1",
    data: BytesLike
  ): Result;

  events: {};
}

export class CallExecutionTreeTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CallExecutionTreeTestInterface;

  functions: {
    extractTargetFromCallGraph1(
      _callGraph: BytesLike,
      _callPath: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string] & {
        targetBlockchainId: BigNumber;
        targetContract: string;
        functionCall: string;
      }
    >;
  };

  extractTargetFromCallGraph1(
    _callGraph: BytesLike,
    _callPath: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, string] & {
      targetBlockchainId: BigNumber;
      targetContract: string;
      functionCall: string;
    }
  >;

  callStatic: {
    extractTargetFromCallGraph1(
      _callGraph: BytesLike,
      _callPath: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string] & {
        targetBlockchainId: BigNumber;
        targetContract: string;
        functionCall: string;
      }
    >;
  };

  filters: {};

  estimateGas: {
    extractTargetFromCallGraph1(
      _callGraph: BytesLike,
      _callPath: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    extractTargetFromCallGraph1(
      _callGraph: BytesLike,
      _callPath: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
